// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAzOZCBxGlzmaLKvggvyc2pI_rqTCquog',
    appId: '1:208016737211:web:06bc95a699387fc5e53a9e',
    messagingSenderId: '208016737211',
    projectId: 'upv-database',
    authDomain: 'upv-database.firebaseapp.com',
    storageBucket: 'upv-database.firebasestorage.app',
    measurementId: 'G-LC0D5L91YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdrJiB-IfO3Xh20UtJb0aJZNX47txMa98',
    appId: '1:208016737211:android:84b088401e856921e53a9e',
    messagingSenderId: '208016737211',
    projectId: 'upv-database',
    storageBucket: 'upv-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPT8LyhkKvFOQ7kEVpgHPx54nyXfHe2fA',
    appId: '1:208016737211:ios:5d03bf8e349d33fae53a9e',
    messagingSenderId: '208016737211',
    projectId: 'upv-database',
    storageBucket: 'upv-database.firebasestorage.app',
    iosBundleId: 'com.example.upv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPT8LyhkKvFOQ7kEVpgHPx54nyXfHe2fA',
    appId: '1:208016737211:ios:5d03bf8e349d33fae53a9e',
    messagingSenderId: '208016737211',
    projectId: 'upv-database',
    storageBucket: 'upv-database.firebasestorage.app',
    iosBundleId: 'com.example.upv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAzOZCBxGlzmaLKvggvyc2pI_rqTCquog',
    appId: '1:208016737211:web:f52866531ebc178ae53a9e',
    messagingSenderId: '208016737211',
    projectId: 'upv-database',
    authDomain: 'upv-database.firebaseapp.com',
    storageBucket: 'upv-database.firebasestorage.app',
    measurementId: 'G-SSP87STMMN',
  );

}